version: "3.3"
services:
  eolearn:
      image: sentinelhub/eolearn:latest-examples
      ports:
        - 8888:8888
      volumes:
        - "./:/home/eolearner"
  fastapi:
    build:
      context: .
      dockerfile: DockerfileWebApi
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
      MAX_WORKERS: 1
    ports:
      - "5000:80"
    volumes:
      - ./satellite_data/:/app/satellite_data/
    depends_on:
      - redis_server
  worker:
    build:
      dockerfile: DockerfileCelery
      context: .
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
    volumes:
      - ./satellite_data/:/celery_tasks/satellite_data/
    depends_on:
      - redis_server
  redis_server:
    image: redis

  flower:
    image: mher/flower
    command: ["celery", "flower", "--broker=redis://redis_server:6379", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis_server

  front:
    build:
      dockerfile: DockerfileFront
      context: .
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.example